//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakraStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class competition
    {
        public string CompetitionsID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<int> TotSales { get; set; }
        public Nullable<int> TotTurnover { get; set; }
        public Nullable<int> DaySales { get; set; }
        public Nullable<int> DayTurnover { get; set; }
        public string Role { get; set; }
        public Nullable<int> Places { get; set; }
        public string CompText { get; set; }
    }
}
