//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakraStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public int GroupID { get; set; }
        public string EmployeeID { get; set; }
        public string MemberID { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
