//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakraStats
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeContext : DbContext
    {
        public HomeContext()
            : base("name=HomeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access> accesses { get; set; }
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<stat> stats { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<carstat> carstats { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<storestat> storestats { get; set; }
        public virtual DbSet<budget> budgets { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<calendar> calendars { get; set; }
        public virtual DbSet<demreport> demreports { get; set; }
    }
}
