//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakraStats
{
    using System;
    using System.Collections.Generic;
    
    public partial class storestat
    {
        public int StatsID { get; set; }
        public string StoreID { get; set; }
        public string ProductID { get; set; }
        public int ProductQty { get; set; }
    
        public virtual product product { get; set; }
        public virtual store store { get; set; }
    }
}
